# Generated by Django 4.2.2 on 2023-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='logForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Form',
            new_name='regForm',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='descrion',
            new_name='description',
        ),
    ]
