# Generated by Django 4.2.2 on 2023-06-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_delete_logform_rename_firstname_regform_bname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regform',
            old_name='bname',
            new_name='branchname',
        ),
        migrations.RenameField(
            model_name='regform',
            old_name='email',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='regform',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='regform',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='regform',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
