# Generated by Django 4.2.2 on 2023-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_rename_bname_regform_branchname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
